### ISSUE TITLE
Issue with npm install SortableJS in MeteorJS project

### ISSUE THREAD

**Issue by Sergeyamir** [SortableJS/sortablejs-meteor#11]
Could you tell me what may be the cause of the problem in installing sortable js with npm command? I see this error in JSON:

```
netx:~/workspace/app (master) $ meteor npm install sortablejs --save
npm ERR! Unexpected token } in JSON at position 11280
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-12-06T10_09_36_253Z-debug.log
```

What the JSON file has that unexpected token?
The mentioned complete log does not give the file name:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'sortablejs' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 0558a99e7e1cc796
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/sortablejs 116ms
8 http fetch GET 200 https://registry.npmjs.org/sortablejs/-/sortablejs-1.7.0.tgz 33ms
9 silly pacote tag manifest for sortablejs@latest fetched in 224ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly saveTree app@
13 silly saveTree └─┬ @babel/runtime@7.0.0-beta.52
13 silly saveTree   ├── core-js@2.5.7
13 silly saveTree   └── regenerator-runtime@0.12.0
14 verbose stack SyntaxError: Unexpected token } in JSON at position 11280
14 verbose stack     at JSON.parse (<anonymous>)
14 verbose stack     at module.exports (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
14 verbose stack     at BB.join (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20)
14 verbose stack     at tryCatcher (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Holder$3._callFunction (eval at generateHolderClass (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
14 verbose stack     at Holder$3.checkFulfillment (eval at generateHolderClass (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
14 verbose stack     at Promise.eval (eval at thenCallback (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
14 verbose stack     at Promise._settlePromise (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
14 verbose stack     at Promise._settlePromise0 (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14 verbose stack     at Promise._settlePromises (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14 verbose stack     at Promise._fulfill (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
14 verbose stack     at Promise._settlePromise (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
14 verbose stack     at Promise._settlePromise0 (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14 verbose stack     at Promise._settlePromises (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14 verbose stack     at Promise._fulfill (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
14 verbose stack     at /home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
14 verbose stack     at /home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
14 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
15 verbose cwd /home/ubuntu/workspace/app
16 verbose Linux 4.9.120-c9
17 verbose argv "/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1_1.1pl6r72.bde6f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "--save" "sortablejs"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error Unexpected token } in JSON at position 11280
21 verbose exit [ 1, true ]

```

**Comment by owen-m1** [comment]
@Sergeyamir This project does not have a maintainer, you are welcomed to try to fix it yourself and I will merge your changes
